export const stateData = {
  postings: [],
  id: "",
  organization: "",
  address: "",
  state: "ON",
  city: "Toronto",
  phone: "",
  website: "",
  email: "",
  category: "",
  role: "",
  role_description: "",
  start_date: new Date(),
  end_date: new Date(),
  created: Date.now(),
  isNoResult: false,
  headerButtonText: "Post Opportunities",
  filteredCategory: "",
};